{% set version = "1.14.3" %}
{% set sha256 = "e4045b6c732d9ce75d571c79f5ac2234edd9ae4f5fa9d59b09705082bdca18c7" %}

package:
  name: sh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sh/sh-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip

  run:
    - python >=2.7
    - __unix

test:
  imports:
    - sh

about:
  home: https://github.com/amoffat/sh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python subprocess interface

extra:
  recipe-maintainers:
    - jakirkham
