{% set name = "sh" %}
{% set version = "1.13.1" %}
{% set sha256 = "97a3d2205e3c6a842d87ebbc9ae93acae5a352b1bc4609b428d0fd5bb9e286a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - sh

about:
  home: https://github.com/amoffat/sh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python subprocess interface

extra:
  recipe-maintainers:
    - jakirkham
